# Generated by Django 4.1.3 on 2023-09-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscribers_subscriberscategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberscategories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subscriberscategories',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
        migrations.DeleteModel(
            name='SubscribersCategories',
        ),
    ]
